name: mordredenv
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.8
  - mordred
  - numpy==1.19.5
  - pandas==1.3.4
  - networkx==2.2
  - matplotlib >=3.6.0, <3.7
  - ipywidgets==7.5.1
  - conda-forge::scikit-learn
  - joblib
  - rdkit
  - selfies
  - pyarrow
